/* eslint-disable react-refresh/only-export-components */
export * from "./MyHotels"
export * from "./Register"
export * from "./SignIn"
export * from "./AddHotel"
export * from "./EditHotel"
export * from "./Search"
export * from "./Detail"
export * from "./Booking"